from __future__ import annotations

from typing import Optional
from schemas import Profile, Lesson, LessonSection, Quiz, Question, Answer, Result


def _distribute_minutes(total_minutes: int, num_sections: int = 6) -> list[int]:
    """
    Distributes total_minutes across 6 lesson sections such that
    the sum is strictly equal to total_minutes.
    """
    if total_minutes <= 0:
        return [0] * num_sections
    if total_minutes < num_sections:
        res = [0] * num_sections
        for i in range(total_minutes):
            res[i] = 1
        return res

    # Base weights for: [intro, explain, example, practice, quiz, recap]
    weights = [1, 3, 3, 4, 2, 2]
    total_weight = sum(weights)
    alloc = [max(1, int(total_minutes * w / total_weight)) for w in weights]
    diff = total_minutes - sum(alloc)

    # Priority order for distributing remaining minutes:
    # practice, example, explain, quiz, recap, intro
    priority = [3, 2, 1, 4, 5, 0]
    idx = 0
    while diff > 0:
        alloc[priority[idx % len(priority)]] += 1
        diff -= 1
        idx += 1
    while diff < 0:
        target = priority[idx % len(priority)]
        if alloc[target] > 1:
            alloc[target] -= 1
            diff += 1
        idx += 1
        if idx > 50:
            alloc[0] += diff
            break

    return alloc


# Master repository of mock quiz questions for Python loops
MOCK_QUESTIONS: dict[str, Question] = {
    "q1": Question(
        id="q1",
        concept_id="range_bounds",
        question="What sequence of numbers does `range(0, 5)` generate?",
        options=["0, 1, 2, 3, 4", "0, 1, 2, 3, 4, 5", "1, 2, 3, 4, 5", "1, 2, 3, 4"],
        correct_answer="0, 1, 2, 3, 4",
        explanation="In Python, `range(start, stop)` includes `start` (0) but stops strictly before `stop` (5)."
    ),
    "q2": Question(
        id="q2",
        concept_id="loop_body",
        question="How many times will this loop print 'Hello'?\n\n```python\nfor i in range(3):\n    print('Hello')\n```",
        options=["2 times", "3 times", "4 times", "0 times"],
        correct_answer="3 times",
        explanation="The loop executes its indented body for each value generated by `range(3)`: i=0, i=1, and i=2."
    ),
    "q3": Question(
        id="q3",
        concept_id="range_bounds",
        question="What is the output of `list(range(2, 6))`?",
        options=["[2, 3, 4, 5, 6]", "[2, 3, 4, 5]", "[3, 4, 5, 6]", "[2, 4, 6]"],
        correct_answer="[2, 3, 4, 5]",
        explanation="The range starts at 2 (inclusive) and terminates before 6 (exclusive), yielding [2, 3, 4, 5]."
    ),
    "q4": Question(
        id="q4",
        concept_id="loop_body",
        question="What is the final value of `total` after execution?\n\n```python\ntotal = 0\nfor x in [1, 2, 3]:\n    total += x\n```",
        options=["3", "5", "6", "0"],
        correct_answer="6",
        explanation="The body updates `total` in every pass: 0 + 1 = 1, 1 + 2 = 3, 3 + 3 = 6."
    ),
    "q5": Question(
        id="q5",
        concept_id="range_bounds",
        question="Which expression generates integers from 1 through 5 inclusive: `1, 2, 3, 4, 5`?",
        options=["range(1, 5)", "range(1, 6)", "range(5)", "range(0, 5)"],
        correct_answer="range(1, 6)",
        explanation="Because `stop` is exclusive, specifying 6 stops after 5 is produced."
    ),
}


def generate_lesson(profile: Profile, weak_concept: Optional[str] = None) -> Lesson:
    """
    Generates a structured Python loops lesson with 6 sections:
    intro, explain, example, practice, quiz, recap.
    The section durations sum strictly to profile.minutes.
    The example section includes animation={'component': 'range_viz', 'start': 0, 'end': 5}.
    """
    total_minutes = profile.minutes
    durations = _distribute_minutes(total_minutes, num_sections=6)

    focus_note = ""
    if weak_concept:
        focus_note = f"\n\n*Special Focus: Reinforcing **{weak_concept}** concepts tailored for {profile.name}.*"

    sections: list[LessonSection] = [
        LessonSection(
            id="sec_1_intro",
            type="intro",
            title="Introduction to Python Loops",
            minutes=durations[0],
            content=(
                f"Welcome, {profile.name}! In this session, you will master Python `for` loops.\n\n"
                "Loops allow programs to repeat actions efficiently without redundant code. "
                "Instead of copying and pasting instructions, a loop processes items one-by-one."
                f"{focus_note}"
            ),
        ),
        LessonSection(
            id="sec_2_explain",
            type="explain",
            title="The Structure of a For Loop and range()",
            minutes=durations[1],
            content=(
                "A Python `for` loop iterates over a sequence of items. The most common tool "
                "used with `for` loops is the built-in `range()` function.\n\n"
                "Key Rules:\n"
                "1. **Start Bound**: The first number in `range(start, stop)` is inclusive.\n"
                "2. **Stop Bound**: The second number is exclusive (the loop stops before reaching it).\n"
                "3. **Loop Body**: All indented lines under the `for` statement execute once per item."
            ),
            code="for item in range(start, stop):\n    # indented code runs each cycle\n    do_something(item)",
        ),
        LessonSection(
            id="sec_3_example",
            type="example",
            title="Visualizing range(0, 5) Step-by-Step",
            minutes=durations[2],
            content=(
                "Let's trace `range(0, 5)`. Notice that even though the stop parameter is 5, "
                "the loop generates 0, 1, 2, 3, and 4 (5 total iterations).\n\n"
                "Inspect the visual range stepper below to see how each iteration updates `i`."
            ),
            animation={"component": "range_viz", "start": 0, "end": 5},
            code="for i in range(0, 5):\n    print(f'Current i is: {i}')",
        ),
        LessonSection(
            id="sec_4_practice",
            type="practice",
            title="Hands-On Practice Exercises",
            minutes=durations[3],
            content=(
                "Now it is your turn to apply the concepts! Try writing loops to solve these challenges:\n\n"
                "1. **Sum numbers 1 to 5**: Use `range(1, 6)` and an accumulator variable.\n"
                "2. **Even numbers**: Generate even numbers between 0 and 10 using `range(0, 11, 2)`."
            ),
            code="# Exercise 1\ntotal = 0\nfor num in range(1, 6):\n    total += num\nprint('Sum:', total)",
        ),
        LessonSection(
            id="sec_5_quiz",
            type="quiz",
            title="Knowledge Checkpoint",
            minutes=durations[4],
            content=(
                "Test your understanding before wrapping up! In the next step, you will be given a "
                "5-question quiz covering `range_bounds` and `loop_body` mechanics."
            ),
        ),
        LessonSection(
            id="sec_6_recap",
            type="recap",
            title="Session Recap & Key Takeaways",
            minutes=durations[5],
            content=(
                "Awesome job completing the lesson! Remember:\n\n"
                "- `range(a, b)` generates values from `a` up to `b - 1`.\n"
                "- The loop body executes once for each element produced.\n"
                "- Indentation defines what belongs inside the loop body."
            ),
        ),
    ]

    return Lesson(
        id="lesson_python_loops_01",
        topic="Python For Loops & range()",
        total_minutes=total_minutes,
        sections=sections,
        weak_concept=weak_concept,
    )


def generate_quiz(concept_ids: list[str]) -> Quiz:
    """
    Generates a 5-question quiz covering Python loops.
    Uses concept_ids 'range_bounds' and 'loop_body'.
    """
    # Filter or select questions based on requested concepts, ensuring all 5 questions are returned
    target_concepts = set(concept_ids) if concept_ids else {"range_bounds", "loop_body"}

    selected_questions: list[Question] = []
    # Guarantee 5 questions
    for q in MOCK_QUESTIONS.values():
        if q.concept_id in target_concepts or len(selected_questions) < 5:
            selected_questions.append(q)
        if len(selected_questions) == 5:
            break

    # If fewer than 5 matched, backfill from remaining
    if len(selected_questions) < 5:
        for q in MOCK_QUESTIONS.values():
            if q not in selected_questions:
                selected_questions.append(q)
            if len(selected_questions) == 5:
                break

    return Quiz(
        id="quiz_python_loops_01",
        topic="Python Loops: Bounds & Loop Execution",
        concept_ids=list(target_concepts),
        questions=selected_questions,
    )


def submit_answers(answers: list[Answer]) -> Result:
    """
    Evaluates submitted answers, scores each question, and identifies
    any weak concept IDs from incorrect answers.
    """
    score = 0
    total = len(MOCK_QUESTIONS)
    weak_concepts_set: set[str] = set()
    details: list[dict] = []

    answer_map = {ans.question_id: ans.selected_answer for ans in answers}

    for qid, q in MOCK_QUESTIONS.items():
        user_choice = answer_map.get(qid, "").strip()
        is_correct = user_choice == q.correct_answer.strip()

        if is_correct:
            score += 1
        else:
            weak_concepts_set.add(q.concept_id)

        details.append({
            "question_id": q.id,
            "concept_id": q.concept_id,
            "question": q.question,
            "selected_answer": user_choice,
            "correct_answer": q.correct_answer,
            "is_correct": is_correct,
            "explanation": q.explanation,
        })

    percentage = round((score / total) * 100, 1) if total > 0 else 0.0
    passed = percentage >= 60.0

    if score == total:
        feedback = "Perfect score! You have a crystal-clear understanding of loop bounds and loop execution."
    elif passed:
        feedback = "Great job! You passed the quiz. Review the highlighted concepts to refine your skills."
    else:
        feedback = "Keep practicing! Review the lesson material for the concepts you missed."

    return Result(
        score=score,
        total=total,
        percentage=percentage,
        passed=passed,
        feedback=feedback,
        weak_concepts=sorted(list(weak_concepts_set)),
        details=details,
    )
